/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RS485.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Rx_Int.h"
#include "Temp_CLK.h"
#include "MAX31855_MISO_aliases.h"
#include "MAX31855_MISO.h"
#include "Temp_CS.h"
#include "MAX31855_CS_aliases.h"
#include "MAX31855_CLK_aliases.h"
#include "MAX31855_CLK.h"
#include "Timer.h"
#include "Timer_Int.h"
#include "Wire1_aliases.h"
#include "Wire1.h"
#include "PSI.h"
#include "Movement_aliases.h"
#include "Movement.h"
#include "AMux.h"
#include "Pressure_aliases.h"
#include "Pressure.h"
#include "LED_aliases.h"
#include "LED.h"
#include "AC_aliases.h"
#include "AC.h"
#include "AC2_aliases.h"
#include "AC2.h"
#include "RS485_IntClock.h"
#include "PSI_AMux.h"
#include "PSI_Ext_CP_Clk.h"
#include "PSI_IRQ.h"
#include "PSI_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

